# Generated by Django 6.0 on 2025-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
