# Generated by Django 6.0 on 2025-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_driver_lat_order_driver_lng_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
