# Generated by Django 6.0 on 2026-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
